In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

KAMUS ASPEK

In [ ]:
# @title
# ==============================
# CELL 0: KAMUS KEYWORD ASPEK (FINAL)
# ==============================
!pip install -q Sastrawi scikit-learn seaborn
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()
import pandas as pd
import re
import os

DATA_DIR = "/content/drive/MyDrive/skripsi/dataset/kamus"
OUT_KAMUS_KEYWORD = os.path.join(DATA_DIR, "kamus_aspek.csv")

# =========================
# DEFINISI KEYWORDS FINAL
# =========================
ASPECT_KEYWORDS = {

    # =========================
    # 1️⃣ HARGA & PEMBAYARAN
    # =========================
    "Harga & Pembayaran": [
        "harga","biaya","tarif","langganan","paket","premium","vip",
        "bayar","pembayaran","tagihan","billing","invoice","saldo",
        "refund","voucher","diskon","promo","cashback","kupon",
        "transaksi","pajak","beli","uang","murah","mahal","gratis",
        "kemahalan","berlangganan","auto debit","potong saldo",
        "perpanjang","unsubscribe","berhenti langganan"
    ],

    # =========================
    # 2️⃣ AKUN & AKSES
    # =========================
    "Akun & Akses": [
        "akun","login","logout","verifikasi","otp","password",
        "sandi","username","email","profil","registrasi",
        "daftar","masuk","keluar","sign in","sign out",
        "kode verifikasi","reset password","ganti password",
        "tidak bisa login","gagal login","logout sendiri",
        "household","perangkat","device","akun terkunci"
    ],

    # =========================
    # 3️⃣ KONTEN
    # =========================
    "Konten": [
        "film","movie","series","serial","drama","drakor","anime",
        "episode","season","judul","tayang","tontonan","acara",
        "show","dokumenter","kartun","katalog","koleksi","genre",
        "trailer","teaser","scene","alur cerita","ceritanya",
        "pemeran","aktor","aktris","subtitle indo","sub indo",
        "tidak lengkap","episode kurang","film lama"
    ],

    # =========================
    # 4️⃣ KUALITAS STREAMING
    # =========================
    "Kualitas Streaming": [
        "video","audio","suara","gambar","resolusi","subtitle",
        "terjemahan","kualitas","buffering","loading","lag",
        "delay","fps","bitrate","glitch","hd","frame","framerate",
        "frame drop","buram","blur","pecah","patah patah",
        "suara kecil","audio hilang","tidak sinkron",
        "loading lama","buffer lama"
    ],

    # =========================
    # 5️⃣ APLIKASI & FITUR
    # =========================
    "Aplikasi & Fitur": [
        "aplikasi","fitur","menu","tampilan","desain","ui","ux",
        "navigasi","search","pencarian","rekomendasi","watchlist",
        "wishlist","download","offline","riwayat","history",
        "notifikasi","pengaturan","setting","mode","dark","light",
        "server","sistem","update","versi","tv","bug","error",
        "crash","force close","keluar sendiri","lemot","lambat",
        "berat","hang","freeze","iklan","ads","advertisement",
        "tidak bisa dibuka","gagal dibuka","loading terus"
    ]
}

# =========================
# RAPIIIN KEYWORDS
# =========================
def clean_kw(k):
    k = str(k).lower().strip()
    k = re.sub(r"\s+", " ", k)
    return k

for asp in ASPECT_KEYWORDS:
    kws = [clean_kw(k) for k in ASPECT_KEYWORDS[asp]]
    kws = [stemmer.stem(k) for k in kws if k != ""]
    ASPECT_KEYWORDS[asp] = sorted(list(set(kws)), key=len, reverse=True)


print("✅ Keyword sudah dirapikan!")
for asp, kws in ASPECT_KEYWORDS.items():
    print(f"{asp}: {len(kws)} keyword")

# =========================
# SAVE KEYWORD TO CSV
# =========================
rows = []
for asp, kws in ASPECT_KEYWORDS.items():
    for kw in kws:
        rows.append({"Aspek": asp, "Keyword": kw})

df_kw = pd.DataFrame(rows)
df_kw.to_csv(OUT_KAMUS_KEYWORD, index=False, encoding="utf-8-sig")

print("\n✅ Saved keyword CSV:", OUT_KAMUS_KEYWORD)
display(df_kw.head(20))

✅ Keyword sudah dirapikan!
Harga & Pembayaran: 30 keyword
Akun & Akses: 26 keyword
Konten: 32 keyword
Kualitas Streaming: 28 keyword
Aplikasi & Fitur: 44 keyword

✅ Saved keyword CSV: /content/drive/MyDrive/skripsi/dataset/kamus/kamus_aspek.csv

                 Aspek        Keyword
0   Harga & Pembayaran  henti langgan
1   Harga & Pembayaran   potong saldo
2   Harga & Pembayaran    unsubscribe
3   Harga & Pembayaran     auto debit
4   Harga & Pembayaran      transaksi
5   Harga & Pembayaran       cashback
6   Harga & Pembayaran        billing
7   Harga & Pembayaran        invoice
8   Harga & Pembayaran        langgan
9   Harga & Pembayaran        panjang
10  Harga & Pembayaran        premium
11  Harga & Pembayaran        voucher
12  Harga & Pembayaran         gratis
13  Harga & Pembayaran         refund
14  Harga & Pembayaran         diskon
15  Harga & Pembayaran          biaya
16  Harga & Pembayaran          tagih
17  Harga & Pembayaran          mahal
18  Harga & Pembayaran          saldo
19  Harga & Pembayaran          promo

KAMUS TYPO

In [ ]:
# ==============================
# CELL: KAMUS KEYWORD ASPEK
# ==============================

!pip install -q Sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()

import pandas as pd
import re
import os

DATA_DIR = "/content/drive/MyDrive/skripsi/dataset/kamus"
OUT_KAMUS_KEYWORD = os.path.join(DATA_DIR, "kamus_aspek.csv")

# =========================
# DEFINISI KEYWORDS (TANPA NEGASI / OPINI)
# =========================
ASPECT_KEYWORDS = {

    "Harga & Pembayaran": [
        "harga","biaya","tarif","langganan","paket","premium","vip",
        "bayar","pembayaran","tagihan","billing","invoice","saldo",
        "refund","voucher","diskon","promo","cashback","kupon",
        "transaksi","pajak","uang","perpanjang","unsubscribe",
        "auto debit","potong saldo","metode bayar","kartu kredit",
        "debit","e wallet","gopay","ovo","dana","shopeepay",
        "masa aktif","berlangganan","berhenti langganan"
    ],

    "Akun & Akses": [
        "akun","login","logout","verifikasi","otp","password",
        "username","email","profil","registrasi","daftar","masuk",
        "keluar","reset password","ganti password","kode verifikasi",
        "akun terkunci","perangkat","device","household",
        "aktivasi","nonaktif","blokir","terkunci","sign in","sign out",
        "tidak bisa masuk","gagal masuk","kode otp"
    ],

    "Konten": [
        "film","movie","series","serial","drama","drakor","anime",
        "episode","season","judul","tayang","tontonan","acara",
        "show","dokumenter","kartun","katalog","koleksi","genre",
        "trailer","teaser","alur cerita","cerita","pemeran",
        "aktor","aktris","subtitle","subjudul","dubbing",
        "episode baru","film baru","update film","judul baru",
        "tayangan","siaran","program"
    ],

    "Kualitas Streaming": [
        "video","audio","suara","gambar","resolusi","kualitas",
        "buffering","loading","lag","delay","fps","bitrate","glitch",
        "hd","frame","framerate","blur","buram","pecah",
        "patah patah","putus putus","tidak sinkron",
        "loading lama","buffer lama","tersendat","macet",
        "kualitas rendah","suara hilang","gambar hilang",
        "sinkronisasi","tidak jernih"
    ],

    "Aplikasi & Fitur": [
        "aplikasi","fitur","menu","tampilan","desain","ui","ux",
        "navigasi","search","pencarian","rekomendasi","watchlist",
        "wishlist","download","offline","riwayat","history",
        "notifikasi","pengaturan","setting","mode","dark","light",
        "server","sistem","update","versi","tv","bug","error","crash",
        "force close","keluar sendiri","hang","freeze",
        "iklan","ads","pop up","layar","halaman",
        "tidak bisa dibuka","gagal dibuka","tidak merespon",
        "loading aplikasi","fitur baru","fitur hilang"
    ]
}

# =========================
# FUNGSI BERSIHKAN KEYWORD
# =========================
def clean_kw(k):
    k = str(k).lower().strip()
    k = re.sub(r"\s+", " ", k)
    return k

# =========================
# STEMMING KONSISTEN DENGAN DATA
# =========================
for asp in ASPECT_KEYWORDS:
    new_kws = []
    for k in ASPECT_KEYWORDS[asp]:
        k = clean_kw(k)

        # STEM SEMUA kata agar cocok dengan clean_text_stem
        stemmed = " ".join([stemmer.stem(word) for word in k.split()])
        new_kws.append(stemmed)

    ASPECT_KEYWORDS[asp] = sorted(list(set(new_kws)), key=len, reverse=True)

print("✅ Keyword aspek sudah distem konsisten dengan data")

# =========================
# SAVE KE CSV
# =========================
rows = []
for asp, kws in ASPECT_KEYWORDS.items():
    for kw in kws:
        rows.append({"Aspek": asp, "Keyword": kw})

df_kw = pd.DataFrame(rows)
df_kw.to_csv(OUT_KAMUS_KEYWORD, index=False, encoding="utf-8-sig")

print("\n💾 Kamus aspek final disimpan di:", OUT_KAMUS_KEYWORD)
display(df_kw.head(20))

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 4.6 MB/s eta 0:00:00
✅ Keyword aspek sudah distem konsisten dengan data

💾 Kamus aspek final disimpan di: /content/drive/MyDrive/skripsi/dataset/kamus/kamus_aspek.csv

                 Aspek        Keyword
0   Harga & Pembayaran  henti langgan
1   Harga & Pembayaran   metode bayar
2   Harga & Pembayaran   kartu kredit
3   Harga & Pembayaran   potong saldo
4   Harga & Pembayaran    unsubscribe
5   Harga & Pembayaran     masa aktif
6   Harga & Pembayaran     auto debit
7   Harga & Pembayaran      transaksi
8   Harga & Pembayaran      shopeepay
9   Harga & Pembayaran       cashback
10  Harga & Pembayaran       e wallet
11  Harga & Pembayaran        panjang
12  Harga & Pembayaran        invoice
13  Harga & Pembayaran        billing
14  Harga & Pembayaran        premium
15  Harga & Pembayaran        voucher
16  Harga & Pembayaran        langgan
17  Harga & Pembayaran         refund
18  Harga & Pembayaran         diskon
19  Harga & Pembayaran          debit

In [ ]:
import pandas as pd
import re
import os

DATA_DIR = "/content/drive/MyDrive/skripsi/dataset/kamus"
OUT_FILE = os.path.join(DATA_DIR, "kamus_typo.csv")

# =========================
# DAFTAR TYPO → BENTUK BAKU
# =========================
NORMALIZATION_DICT = {

    # ======================
    # NEGASI & SINGKATAN UMUM
    # ======================
    "gk": "tidak",
    "ga": "tidak",
    "gak": "tidak",
    "nggak": "tidak",
    "ngga": "tidak",
    "tdk": "tidak",
    "tdak": "tidak",
    "tidk": "tidak",
    "tida": "tidak",

    "yg": "yang",
    "dg": "dengan",
    "dgn": "dengan",
    "dr": "dari",
    "krn": "karena",
    "karna": "karena",

    "utk": "untuk",
    "untk": "untuk",
    "aja": "saja",
    "sm": "sama",
    "trs": "terus",
    "trus": "terus",

    "udh": "sudah",
    "sdh": "sudah",
    "blm": "belum",
    "bkn": "bukan",

    # ======================
    # FRASE NEGASI PENTING
    # ======================
    "gbs": "tidak bisa",
    "gabisa": "tidak bisa",
    "gakbisa": "tidak bisa",
    "ga bisa": "tidak bisa",
    "gk bisa": "tidak bisa",

    "gaboleh": "tidak boleh",
    "gakboleh": "tidak boleh",

    "gk ada": "tidak ada",
    "ga ada": "tidak ada",
    "gak ada": "tidak ada",

    "gk lengkap": "tidak lengkap",
    "ga lengkap": "tidak lengkap",
    "gak lengkap": "tidak lengkap",

    # ======================
    # KATA INTENSITAS
    # ======================
    "bgt": "banget",
    "bgtt": "banget",
    "bngt": "banget",
    "bngtt": "banget",

    # ======================
    # TYPO TEKNIS STREAMING
    # ======================
    "ngelag": "lag",
    "ngelag": "lag",
    "lagg": "lag",

    "ngebug": "bug",
    "bugg": "bug",

    "ngehang": "hang",
    "hangg": "hang",

    "ngeload": "loading",
    "lodinng": "loading",
    "loadingg": "loading",
    "loadng": "loading",

    "buffring": "buffering",
    "bufring": "buffering",
    "bufferng": "buffering",
    "bufferig": "buffering",

    "eror": "error",
    "erro": "error",
    "erorr": "error",
    "errorr": "error",
    "err": "error",

    "cras": "crash",
    "crashh": "crash",

    # ======================
    # PERFORMA / KECEPATAN
    # ======================
    "lemott": "lemot",
    "lemottt": "lemot",
    "lelet": "lemot",
    "lambatt": "lambat",
    "lambattt": "lambat",
    "lambat banget": "lambat",

    # ======================
    # KONTEKS APLIKASI
    # ======================
    "apk": "aplikasi",
    "apknya": "aplikasi",
    "apk nya": "aplikasi",
    "apps": "aplikasi",
    "app": "aplikasi",

    "fiturr": "fitur",

    "menunya": "menu",
    "menunyaa": "menu",

    # ======================
    # LOGIN & AKUN
    # ======================
    "loginnya": "login",
    "loginya": "login",
    "loginn": "login",
    "log in": "login",
    "signin": "login",
    "sign in": "login",

    "logoutt": "logout",
    "log out": "logout",

    # ======================
    # FILM & KONTEN
    # ======================
    "filmnnya": "filmnya",
    "filmnyaa": "filmnya",
    "moviee": "movie",

    "seris": "series",
    "episod": "episode",

    "lengkapp": "lengkap",
    "lengkappp": "lengkap",
    "lengkap banget": "lengkap",

    # ======================
    # SUBTITLE
    # ======================
    "sub": "subtitle",
    "subnya": "subtitle",
    "sub nya": "subtitle",
    "subtitel": "subtitle",
    "subtittle": "subtitle",
    "sub indo": "subtitle",
    "subindo": "subtitle",

    # ======================
    # DOWNLOAD
    # ======================
    "donlod": "download",
    "downlod": "download",
    "downloaded": "download",

    # ======================
    # HARGA
    # ======================
    "mahalnya": "mahal",
    "kemahalan": "mahal",
    "mahal bgt": "mahal",
    "mahal banget": "mahal",

    "murahh": "murah",

    # ======================
    # PEMBAYARAN
    # ======================
    "bayarr": "bayar",
    "bayarrnya": "bayar",
    "bayarrr": "bayar",

    "langganann": "langganan",
    "langganan nya": "langganan",

    "unsubs": "unsubscribe",
    "unsub": "unsubscribe",
}


# =========================
# RAPIKAN & JADIKAN DATAFRAME
# =========================
rows = []
for typo, normal in NORMALIZATION_DICT.items():
    typo_clean = re.sub(r"\s+", " ", typo.strip().lower())
    normal_clean = re.sub(r"\s+", " ", normal.strip().lower())
    rows.append({"typo": typo_clean, "normal": normal_clean})

df_typo = pd.DataFrame(rows).drop_duplicates().sort_values("typo")

print("✅ Total entri kamus typo:", len(df_typo))
display(df_typo.head(20))

# =========================
# SAVE KE CSV
# =========================
df_typo.to_csv(OUT_FILE, index=False, encoding="utf-8-sig")
print("\n💾 Kamus typo disimpan di:", OUT_FILE)

kalo untuk bagian ini gimana